// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAttjaOSe49sk8rNYNHlh8bOQYTVXoJnXI',
    appId: '1:907097113298:web:0dc7b314e945ce4ee1230b',
    messagingSenderId: '907097113298',
    projectId: 'myapplication-25392609',
    authDomain: 'myapplication-25392609.firebaseapp.com',
    storageBucket: 'myapplication-25392609.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCavVNYIqAY7ZmsmXA9OOJX2JhQcOA5MeA',
    appId: '1:907097113298:android:e82e3e67c6e0b81de1230b',
    messagingSenderId: '907097113298',
    projectId: 'myapplication-25392609',
    storageBucket: 'myapplication-25392609.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsK5y8Uj1FU4HdqHNMyD1nHBIHY5iRp9g',
    appId: '1:907097113298:ios:7e315e34b5d45a70e1230b',
    messagingSenderId: '907097113298',
    projectId: 'myapplication-25392609',
    storageBucket: 'myapplication-25392609.firebasestorage.app',
    iosBundleId: 'com.example.stockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsK5y8Uj1FU4HdqHNMyD1nHBIHY5iRp9g',
    appId: '1:907097113298:ios:7e315e34b5d45a70e1230b',
    messagingSenderId: '907097113298',
    projectId: 'myapplication-25392609',
    storageBucket: 'myapplication-25392609.firebasestorage.app',
    iosBundleId: 'com.example.stockApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAttjaOSe49sk8rNYNHlh8bOQYTVXoJnXI',
    appId: '1:907097113298:web:1fe05ffb033423a2e1230b',
    messagingSenderId: '907097113298',
    projectId: 'myapplication-25392609',
    authDomain: 'myapplication-25392609.firebaseapp.com',
    storageBucket: 'myapplication-25392609.firebasestorage.app',
  );
}
