// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVT81FKL8AISHOHBoQkqmqzSzk88bzG84',
    appId: '1:190600080314:web:c2a7d786e61c7f1acf0b83',
    messagingSenderId: '190600080314',
    projectId: 'dastock-11239',
    authDomain: 'dastock-11239.firebaseapp.com',
    storageBucket: 'dastock-11239.firebasestorage.app',
    measurementId: 'G-GP6N2WDN70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoOyUPxwr0FrxM0NkEEE3VeSPITInUwII',
    appId: '1:190600080314:android:db530140a998fcdecf0b83',
    messagingSenderId: '190600080314',
    projectId: 'dastock-11239',
    storageBucket: 'dastock-11239.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF5UjB93kXiPjkfCoToMTHnLymxjQoBG0',
    appId: '1:190600080314:ios:65a86348d02a4557cf0b83',
    messagingSenderId: '190600080314',
    projectId: 'dastock-11239',
    storageBucket: 'dastock-11239.firebasestorage.app',
    iosBundleId: 'com.example.stockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF5UjB93kXiPjkfCoToMTHnLymxjQoBG0',
    appId: '1:190600080314:ios:65a86348d02a4557cf0b83',
    messagingSenderId: '190600080314',
    projectId: 'dastock-11239',
    storageBucket: 'dastock-11239.firebasestorage.app',
    iosBundleId: 'com.example.stockApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVT81FKL8AISHOHBoQkqmqzSzk88bzG84',
    appId: '1:190600080314:web:b17fc934eae7014fcf0b83',
    messagingSenderId: '190600080314',
    projectId: 'dastock-11239',
    authDomain: 'dastock-11239.firebaseapp.com',
    storageBucket: 'dastock-11239.firebasestorage.app',
    measurementId: 'G-VVJEVB7XD4',
  );

}